### ISSUE TITLE
`external_product` does not work in Concrete 1.0.1

### ISSUE THREAD

**Issue by georgio** [zama-ai/concrete-core#277]
**Describe the bug**
Running the `external_product` function or any other function which calls it does nothing.

**To Reproduce**
Clone and run the main function from this repository: https://github.com/georgio/external-product-fail/blob/main/src/main.rs#L62

**Expected behaviour**
`out` should contain the external product of the two ciphertexts

**Evidence**
You can check the output of main, and try to tweak the initial value of `out`

**Configuration(please complete the following information):**
- nightly-aarch64-apple-darwin (MacBookPro17,1; macOS 13.0.1)
- nightly-x86_64-apple-darwin (MacBookPro17,1; macOS 13.0.1)
- nightly-2022-07-05-x86_64-unknown-linux-gnu (i5-6500; Rocky Linux 8.6 (Green Obsidian))
- nightly-x86_64-unknown-linux-gnu (i5-6500; Rocky Linux 8.6 (Green Obsidian))

**Comment by agnesLeroy** [comment]
Hello! Looking at your code it seems that the problem is that you're creating an empty GLWE ciphertext to perform the external product: so the result of the product is zero. Instead what you can do is encrypt a plaintext vector in the GLWE ciphertext, then do the multiplication with the GGSW that encrypts a plaintext:
```
fn main() {
     let mut fft_engine = FftEngine::new(()).unwrap();

     let raw_input = vec![3_u64 << 59; 1024];
     let noise = Variance(2_f64.powf(-104.));
     const UNSAFE_SECRET: u128 = 0;
     let mut engine = DefaultEngine::new(Box::new(UnixSeeder::new(UNSAFE_SECRET))).unwrap();
     let plaintext_vector: PlaintextVector64 = engine.create_plaintext_vector_from(&raw_input)
         .unwrap();
     let ggsw_pt: Plaintext64 = engine.create_plaintext_from(&1).unwrap();
     let key: GlweSecretKey64 = engine
         .generate_new_glwe_secret_key(GlweDimension(2), PolynomialSize(1024))
         .unwrap();

     let B = DecompositionBaseLog(2);
     let ell = DecompositionLevelCount(12);
     let c: GgswCiphertext64 = engine
         .encrypt_scalar_ggsw_ciphertext(&key, &ggsw_pt, noise, ell, B)
         .unwrap();
     let complex_c: FftFourierGgswCiphertext64 = fft_engine.convert_ggsw_ciphertext(&c).unwrap();
     let ct = engine.encrypt_glwe_ciphertext(&key, &plaintext_vector, noise).unwrap();
     let mut ct_out = engine.zero_encrypt_glwe_ciphertext(&key, noise).unwrap();
     fft_engine.discard_compute_external_product_glwe_ciphertext_ggsw_ciphertext(
         &ct,
         &complex_c,
         &mut ct_out,
     );

     println!("output ct: {:?}", ct_out);
 }
```
I hope this helps!

**Comment by georgio** [comment]
This works!! Thank you very much :-) It seems like we have been doing something wrong in the initialisation indeed.
